### ISSUE TITLE
syntax problem

### ISSUE THREAD

**Issue by SinaShateri** [masterdehghani/Navbar#8]
![image](https://user-images.githubusercontent.com/76934868/146006597-29fd6acf-dd85-451c-8efe-e4c6b1bf2430.png)

ba tavajog be ax bala 2 moshkel syntaxi  vojood darad ke bayad (</p>) dar khat 612 va (") dar khat 621 delete beshe ...

**Comment by masterdehghani** [comment]
Exactly 💯
